// Catálogo PSE Power Batteries — 71 modelos.
// Generado 2026-07-22 desde fichas técnicas públicas: stondemand.mx (Power-Sonic, Dynasty C&D,
// Genesis EnerSys) y bateriaskaisemexico.com (Kaise).
// TODO: reemplazar `imagen` (hoy apunta a wixstatic de Kaise) por fotos propias.

export type Marca = "Power-Sonic" | "Kaise" | "Dynasty" | "Genesis";

export type Bateria = {
  id: string;
  marca: Marca;
  serie: string;
  modelo: string;
  volt: number;
  ah: number;
  tipo: string;
  medidas: string | null;
  peso: number | null;
  terminal: string | null;
  imagen: string | null;
  fuente: string;
};

export const CATALOGO: Bateria[] = [
  {
    "id": "dynasty-ups12-100mr",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 100MR",
    "volt": 12.0,
    "ah": 26.0,
    "tipo": "Respaldo / VRLA",
    "medidas": "166.2 × 131.3 × 174.3 mm",
    "peso": 10.0,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-100mr"
  },
  {
    "id": "dynasty-ups12-150mr",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 150MR",
    "volt": 12.0,
    "ah": 34.6,
    "tipo": "Respaldo / VRLA",
    "medidas": "197.1 × 131.9 × 172.7 mm",
    "peso": 12.4,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-150mr"
  },
  {
    "id": "dynasty-ups12-210mr",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 210MR",
    "volt": 12.0,
    "ah": 53.8,
    "tipo": "Respaldo / VRLA",
    "medidas": "228.6 × 139.2 × 205.1 mm",
    "peso": 18.0,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-210mr"
  },
  {
    "id": "dynasty-ups12-305plp",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 305PLP",
    "volt": 12.0,
    "ah": 78.0,
    "tipo": "Respaldo / VRLA",
    "medidas": "260.9 × 173.4 × 203.5 mm",
    "peso": 26.5,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-305plp"
  },
  {
    "id": "dynasty-ups12-300mr",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 300MR",
    "volt": 12.0,
    "ah": 78.6,
    "tipo": "Respaldo / VRLA",
    "medidas": "260.9 × 173.4 × 203.5 mm",
    "peso": 26.5,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-300mr"
  },
  {
    "id": "dynasty-ups12-350mr",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 350MR",
    "volt": 12.0,
    "ah": 93.2,
    "tipo": "Respaldo / VRLA",
    "medidas": "305.8 × 173.4 × 204.8 mm",
    "peso": 30.5,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-350mr"
  },
  {
    "id": "dynasty-ups12-355plp",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 355PLP",
    "volt": 12.0,
    "ah": 94.0,
    "tipo": "Respaldo / VRLA",
    "medidas": "305.8 × 173.4 × 204.8 mm",
    "peso": 30.5,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-355plp"
  },
  {
    "id": "dynasty-ups12-400mr",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 400MR",
    "volt": 12.0,
    "ah": 103.0,
    "tipo": "Respaldo / VRLA",
    "medidas": "340.9 × 172.7 × 216.4 mm",
    "peso": 34.4,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-400mr"
  },
  {
    "id": "dynasty-ups12-405plp",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 405PLP",
    "volt": 12.0,
    "ah": 103.0,
    "tipo": "Respaldo / VRLA",
    "medidas": "340.9 × 172.4 × 216.4 mm",
    "peso": 30.5,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-405plp"
  },
  {
    "id": "dynasty-ups12-495plp",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 495PLP",
    "volt": 12.0,
    "ah": 140.0,
    "tipo": "Respaldo / VRLA",
    "medidas": "344.7 × 172.4 × 277.7 mm",
    "peso": 45.4,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-495plp"
  },
  {
    "id": "dynasty-ups12-490mr",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 490MR",
    "volt": 12.0,
    "ah": 141.2,
    "tipo": "Respaldo / VRLA",
    "medidas": "344.7 × 172.7 × 277.7 mm",
    "peso": 45.0,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-490mr"
  },
  {
    "id": "dynasty-ups12-545plp",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 545PLP",
    "volt": 12.0,
    "ah": 148.0,
    "tipo": "Respaldo / VRLA",
    "medidas": "344.7 × 172.4 × 277.7 mm",
    "peso": 45.4,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-545plp"
  },
  {
    "id": "dynasty-ups12-540mr",
    "marca": "Dynasty",
    "serie": "UPS12",
    "modelo": "UPS12 540MR",
    "volt": 12.0,
    "ah": 149.0,
    "tipo": "Respaldo / VRLA",
    "medidas": "344.7 × 172.7 × 277.7 mm",
    "peso": 45.0,
    "terminal": "Tornillo",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/dynasty-cd-technologies/ups12-540mr"
  },
  {
    "id": "genesis-np5-12",
    "marca": "Genesis",
    "serie": "NP",
    "modelo": "NP5 12",
    "volt": 12.0,
    "ah": 5.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "90 × 70 × 107 mm",
    "peso": 1.7,
    "terminal": "F1/F2",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/genesis-enersys/np-series/np5-12"
  },
  {
    "id": "genesis-np7-12",
    "marca": "Genesis",
    "serie": "NP",
    "modelo": "NP7 12",
    "volt": 12.0,
    "ah": 7.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "151 × 65 × 100 mm",
    "peso": 2.4,
    "terminal": "F1/F2",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/genesis-enersys/np-series/np7-12"
  },
  {
    "id": "genesis-np9-12",
    "marca": "Genesis",
    "serie": "NP",
    "modelo": "NP9 12",
    "volt": 12.0,
    "ah": 9.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "151 × 65 × 100 mm",
    "peso": 2.5,
    "terminal": "F2",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/genesis-enersys/np-series/np9-12"
  },
  {
    "id": "genesis-np18-12-nb",
    "marca": "Genesis",
    "serie": "NP",
    "modelo": "NP18 12 NB",
    "volt": 12.0,
    "ah": 17.2,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "181 × 76 × 167 mm",
    "peso": 6.17,
    "terminal": "NB",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/genesis-enersys/np-series/np18-12-nb"
  },
  {
    "id": "genesis-np24-12-nb",
    "marca": "Genesis",
    "serie": "NP",
    "modelo": "NP24 12 NB",
    "volt": 12.0,
    "ah": 24.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "166 × 175 × 125 mm",
    "peso": 9.07,
    "terminal": "NB",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/genesis-enersys/np-series/np24-12-nb"
  },
  {
    "id": "genesis-np33-12-nb",
    "marca": "Genesis",
    "serie": "NP",
    "modelo": "NP33 12 NB",
    "volt": 12.0,
    "ah": 33.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "197 × 131 × 158 mm",
    "peso": 11.39,
    "terminal": "NB",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/genesis-enersys/np-series/np33-12-nb"
  },
  {
    "id": "genesis-np55-12-nb",
    "marca": "Genesis",
    "serie": "NP",
    "modelo": "NP55 12 NB",
    "volt": 12.0,
    "ah": 55.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "197 × 131 × 158 mm",
    "peso": 11.39,
    "terminal": "NB",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/genesis-enersys/np-series/np55-12-nb"
  },
  {
    "id": "kaise-kb-1245",
    "marca": "Kaise",
    "serie": "KB",
    "modelo": "KB 1245",
    "volt": 12.0,
    "ah": 4.5,
    "tipo": "Respaldo / Seguridad",
    "medidas": "90 × 70 × 101 mm",
    "peso": 1.55,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_a2a961dd2a8243beae00094ec01ee463~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-1245"
  },
  {
    "id": "kaise-kb-125",
    "marca": "Kaise",
    "serie": "KB",
    "modelo": "KB 125",
    "volt": 12.0,
    "ah": 5.0,
    "tipo": "Respaldo / Seguridad",
    "medidas": null,
    "peso": 1.5,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_372cd134452d4feeba251e2f7637fd42~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kb-125"
  },
  {
    "id": "kaise-kb-127s",
    "marca": "Kaise",
    "serie": "KB",
    "modelo": "KB 127S",
    "volt": 12.0,
    "ah": 7.0,
    "tipo": "Respaldo / Seguridad",
    "medidas": "151 × 65 × 94 mm",
    "peso": null,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_7ff515a2876a461e93a1507ce526e8cc~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kb-127s"
  },
  {
    "id": "kaise-kb-1272",
    "marca": "Kaise",
    "serie": "KB",
    "modelo": "KB 1272",
    "volt": 12.0,
    "ah": 7.2,
    "tipo": "Respaldo / Seguridad",
    "medidas": "151 × 65 × 93 mm",
    "peso": 2.32,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_90ee31b324fa4578a3772857e422f8a7~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kb-1272"
  },
  {
    "id": "kaise-kb-1290",
    "marca": "Kaise",
    "serie": "KB",
    "modelo": "KB 1290",
    "volt": 12.0,
    "ah": 9.0,
    "tipo": "Respaldo / Seguridad",
    "medidas": "151 × 65 × 94 mm",
    "peso": 2.8,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_18f704c0878944899d9dfbb03ed0a80a~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kb-1290"
  },
  {
    "id": "kaise-kb-12120",
    "marca": "Kaise",
    "serie": "KB",
    "modelo": "KB 12120",
    "volt": 12.0,
    "ah": 12.0,
    "tipo": "Respaldo / Seguridad",
    "medidas": "151 × 98 × 97 mm",
    "peso": 3.7,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_d4a1f2f90a1745a2a69d6ce1caab44fd~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kb-12120"
  },
  {
    "id": "kaise-kb-12180",
    "marca": "Kaise",
    "serie": "KB",
    "modelo": "KB 12180",
    "volt": 12.0,
    "ah": 18.0,
    "tipo": "Respaldo / Seguridad",
    "medidas": "181.5 × 1675 × 1675 mm",
    "peso": 5.4,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_5db910097d984421b996e2bd2639ed59~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kb-12180"
  },
  {
    "id": "kaise-kb-12260",
    "marca": "Kaise",
    "serie": "KB",
    "modelo": "KB 12260",
    "volt": 12.0,
    "ah": 26.0,
    "tipo": "Respaldo / Seguridad",
    "medidas": "165 × 175 × 125 mm",
    "peso": 9.75,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_1884b78652ab4976bc1c9c8135b3030b~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kb-12260"
  },
  {
    "id": "kaise-kb-12330",
    "marca": "Kaise",
    "serie": "KB",
    "modelo": "KB 12330",
    "volt": 12,
    "ah": 33.0,
    "tipo": "Respaldo / Seguridad",
    "medidas": "195 × 130 × 155 mm",
    "peso": 11.0,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_2d883690c12c4378becf2c9d176030c0~mv2.png/v1/fit/w_500,h_500,q_90/file.png",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kb-12330"
  },
  {
    "id": "kaise-kbl12400",
    "marca": "Kaise",
    "serie": "KBL",
    "modelo": "KBL12400",
    "volt": 12.0,
    "ah": 40.0,
    "tipo": "Ciclo profundo AGM",
    "medidas": "197.5 × 165.5 × 170 mm",
    "peso": 13.8,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_fa167b11b9f2485f8316bd21ce2d6777~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kbl12400"
  },
  {
    "id": "kaise-kbl12550",
    "marca": "Kaise",
    "serie": "KBL",
    "modelo": "KBL12550",
    "volt": 12.0,
    "ah": 55.0,
    "tipo": "Ciclo profundo AGM",
    "medidas": "224 × 132 × 205 mm",
    "peso": 17.3,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_3080fe0109744b6ea76250733da1076d~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kbl12550"
  },
  {
    "id": "kaise-kbl-12650",
    "marca": "Kaise",
    "serie": "KBL",
    "modelo": "KBL 12650",
    "volt": 12.0,
    "ah": 65.0,
    "tipo": "Ciclo profundo AGM",
    "medidas": "350 × 167 × 179 mm",
    "peso": 22.4,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_dd9b7452d97c4d3c9104b3ef5d47449f~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kbl-12650"
  },
  {
    "id": "kaise-kbl12750",
    "marca": "Kaise",
    "serie": "KBL",
    "modelo": "KBL12750",
    "volt": 12.0,
    "ah": 75.0,
    "tipo": "Ciclo profundo AGM",
    "medidas": "258 × 166 × 206 mm",
    "peso": 24.0,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_4c764dc18ddc49cf97a67f03b6db0874~mv2.png/v1/fit/w_500,h_500,q_90/file.png",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kbl12750"
  },
  {
    "id": "kaise-kbl-121000",
    "marca": "Kaise",
    "serie": "KBL",
    "modelo": "KBL 121000",
    "volt": 12.0,
    "ah": 100.0,
    "tipo": "Ciclo profundo AGM",
    "medidas": "330 × 171 × 215 mm",
    "peso": 29.0,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_faad38751f6d4fcd99bb7bcdcd0fcbd8~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kbl-12100"
  },
  {
    "id": "kaise-kbl-122000",
    "marca": "Kaise",
    "serie": "KBL",
    "modelo": "KBL 122000",
    "volt": 12.0,
    "ah": 200.0,
    "tipo": "Ciclo profundo AGM",
    "medidas": "522 × 238 × 218 mm",
    "peso": 59.1,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_f3624030b7b548dd83f4f07340e12c10~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/bateria-kaise-kbl-12200"
  },
  {
    "id": "kaise-kbl-121500",
    "marca": "Kaise",
    "serie": "KBL",
    "modelo": "KBL 121500",
    "volt": 12,
    "ah": 1500.0,
    "tipo": "Ciclo profundo AGM",
    "medidas": "482 × 170 × 240 mm",
    "peso": 44.8,
    "terminal": null,
    "imagen": "https://static.wixstatic.com/media/daf909_7c46e065077343fd944c2fb5623bc295~mv2.jpg/v1/fit/w_500,h_500,q_90/file.jpg",
    "fuente": "https://www.bateriaskaisemexico.com/product-page/batería-kaise-kbl-121500"
  },
  {
    "id": "power-sonic-pdc-1285",
    "marca": "Power-Sonic",
    "serie": "PDC",
    "modelo": "PDC 1285",
    "volt": 12.0,
    "ah": 8.5,
    "tipo": "Ciclo profundo",
    "medidas": null,
    "peso": 2.5,
    "terminal": "F2",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pdc-series/pdc-1285"
  },
  {
    "id": "power-sonic-pdc-12350",
    "marca": "Power-Sonic",
    "serie": "PDC",
    "modelo": "PDC 12350",
    "volt": 12.0,
    "ah": 35.0,
    "tipo": "Ciclo profundo",
    "medidas": "195 × 130 × 164 mm",
    "peso": 11.3,
    "terminal": "NB3",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pdc-series/pdc-12350"
  },
  {
    "id": "power-sonic-pdc121000",
    "marca": "Power-Sonic",
    "serie": "PDC",
    "modelo": "PDC121000",
    "volt": 12.0,
    "ah": 100.0,
    "tipo": "Ciclo profundo",
    "medidas": "305 × 168 × 228 mm",
    "peso": 30.84,
    "terminal": "U",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pdc-series/pdc121000"
  },
  {
    "id": "power-sonic-pdc122000",
    "marca": "Power-Sonic",
    "serie": "PDC",
    "modelo": "PDC122000",
    "volt": 12.0,
    "ah": 215.0,
    "tipo": "Ciclo profundo",
    "medidas": "522 × 240 × 224 mm",
    "peso": 62.3,
    "terminal": "T11",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pdc-series/pdc122000"
  },
  {
    "id": "power-sonic-pg-12v5-4",
    "marca": "Power-Sonic",
    "serie": "PG",
    "modelo": "PG 12V5 4",
    "volt": 12.0,
    "ah": 5.5,
    "tipo": "Larga vida / General",
    "medidas": "151 × 53 × 99 mm",
    "peso": 2.0,
    "terminal": "F2-F1",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pg-series/pg-12v5-4"
  },
  {
    "id": "power-sonic-pg-12v28-fr",
    "marca": "Power-Sonic",
    "serie": "PG",
    "modelo": "PG 12V28 FR",
    "volt": 12.0,
    "ah": 28.0,
    "tipo": "Larga vida / General",
    "medidas": "166 × 175 × 125 mm",
    "peso": 8.4,
    "terminal": "T12",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pg-series/pg-12v28-fr"
  },
  {
    "id": "power-sonic-pg-12v45-fr",
    "marca": "Power-Sonic",
    "serie": "PG",
    "modelo": "PG 12V45 FR",
    "volt": 12.0,
    "ah": 45.0,
    "tipo": "Larga vida / General",
    "medidas": "197 × 165 × 170 mm",
    "peso": 14.5,
    "terminal": "T6",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pg-series/pg-12v45-fr"
  },
  {
    "id": "power-sonic-pg-12v55-fr",
    "marca": "Power-Sonic",
    "serie": "PG",
    "modelo": "PG 12V55 FR",
    "volt": 12.0,
    "ah": 60.0,
    "tipo": "Larga vida / General",
    "medidas": "229 × 138 × 214 mm",
    "peso": 16.5,
    "terminal": "T6",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pg-series/pg-12v55-fr"
  },
  {
    "id": "power-sonic-pg-12v75t",
    "marca": "Power-Sonic",
    "serie": "PG",
    "modelo": "PG 12V75T",
    "volt": 12.0,
    "ah": 78.0,
    "tipo": "Larga vida / General",
    "medidas": "260 × 168 × 208 mm",
    "peso": 22.7,
    "terminal": "T6",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pg-series/pg-12v75t"
  },
  {
    "id": "power-sonic-pg-12v100-fr",
    "marca": "Power-Sonic",
    "serie": "PG",
    "modelo": "PG 12V100 FR",
    "volt": 12.0,
    "ah": 98.0,
    "tipo": "Larga vida / General",
    "medidas": "306 × 168 × 208 mm",
    "peso": 30.6,
    "terminal": "T6",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pg-series/pg-12v100-fr"
  },
  {
    "id": "power-sonic-pg-12v130-fr",
    "marca": "Power-Sonic",
    "serie": "PG",
    "modelo": "PG 12V130 FR",
    "volt": 12.0,
    "ah": 126.0,
    "tipo": "Larga vida / General",
    "medidas": "408 × 177 × 22 mm",
    "peso": 36.3,
    "terminal": "T11",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pg-series/pg-12v130-fr"
  },
  {
    "id": "power-sonic-pg-12v140-fr",
    "marca": "Power-Sonic",
    "serie": "PG",
    "modelo": "PG 12V140 FR",
    "volt": 12.0,
    "ah": 140.0,
    "tipo": "Larga vida / General",
    "medidas": "345 × 172 × 274 mm",
    "peso": 30.6,
    "terminal": "T6",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pg-series/pg-12v140-fr"
  },
  {
    "id": "power-sonic-pg-12v220-fr",
    "marca": "Power-Sonic",
    "serie": "PG",
    "modelo": "PG 12V220 FR",
    "volt": 12.0,
    "ah": 214.0,
    "tipo": "Larga vida / General",
    "medidas": "522 × 240 × 218 mm",
    "peso": 62.3,
    "terminal": "T11",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/pg-series/pg-12v220-fr"
  },
  {
    "id": "power-sonic-phr-12150",
    "marca": "Power-Sonic",
    "serie": "PHR",
    "modelo": "PHR 12150",
    "volt": 12.0,
    "ah": 36.0,
    "tipo": "Alta descarga (High-Rate)",
    "medidas": "195 × 130 × 167 mm",
    "peso": 10.2,
    "terminal": "T6",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/phr-series/phr-12150"
  },
  {
    "id": "power-sonic-phr-12200",
    "marca": "Power-Sonic",
    "serie": "PHR",
    "modelo": "PHR 12200",
    "volt": 12.0,
    "ah": 58.0,
    "tipo": "Alta descarga (High-Rate)",
    "medidas": "229 × 138 × 203 mm",
    "peso": 17.3,
    "terminal": "T11",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/phr-series/phr-12200"
  },
  {
    "id": "power-sonic-phr-12300",
    "marca": "Power-Sonic",
    "serie": "PHR",
    "modelo": "PHR 12300",
    "volt": 12.0,
    "ah": 82.0,
    "tipo": "Alta descarga (High-Rate)",
    "medidas": null,
    "peso": 23.8,
    "terminal": "T6",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/phr-series/phr-12300"
  },
  {
    "id": "power-sonic-phr-12350",
    "marca": "Power-Sonic",
    "serie": "PHR",
    "modelo": "PHR 12350",
    "volt": 12.0,
    "ah": 95.0,
    "tipo": "Alta descarga (High-Rate)",
    "medidas": null,
    "peso": null,
    "terminal": "T6",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/phr-series/phr-12350"
  },
  {
    "id": "power-sonic-phr-12400",
    "marca": "Power-Sonic",
    "serie": "PHR",
    "modelo": "PHR 12400",
    "volt": 12.0,
    "ah": 110.0,
    "tipo": "Alta descarga (High-Rate)",
    "medidas": null,
    "peso": null,
    "terminal": "T8",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/phr-series/phr-12400"
  },
  {
    "id": "power-sonic-ps-1208wl",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 1208WL",
    "volt": 12.0,
    "ah": 0.8,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "96 × 25 × 62 mm",
    "peso": 0.35,
    "terminal": "F1",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-1208wl"
  },
  {
    "id": "power-sonic-ps-1223",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 1223",
    "volt": 12.0,
    "ah": 2.3,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "182 × 24 × 61 mm",
    "peso": 0.77,
    "terminal": "de",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-1223"
  },
  {
    "id": "power-sonic-ps-1229",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 1229",
    "volt": 12.0,
    "ah": 2.9,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "178 × 35 × 66 mm",
    "peso": 1.04,
    "terminal": "F1",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-1229"
  },
  {
    "id": "power-sonic-ps-1230",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 1230",
    "volt": 12.0,
    "ah": 3.4,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "133 × 67 × 66 mm",
    "peso": 1.32,
    "terminal": "F1",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-1230"
  },
  {
    "id": "power-sonic-ps-1250",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 1250",
    "volt": 12.0,
    "ah": 5.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "90 × 70 × 107 mm",
    "peso": 1.59,
    "terminal": "F1",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-1250"
  },
  {
    "id": "power-sonic-ps-1270",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 1270",
    "volt": 12.0,
    "ah": 7.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "151 × 65 × 98 mm",
    "peso": 2.18,
    "terminal": "F1/F2",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-1270"
  },
  {
    "id": "power-sonic-ps-1290",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 1290",
    "volt": 12.0,
    "ah": 9.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "151 × 65 × 98 mm",
    "peso": 2.72,
    "terminal": "F2",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-1290"
  },
  {
    "id": "power-sonic-ps-12120",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 12120",
    "volt": 12.0,
    "ah": 12.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "151 × 98 × 98 mm",
    "peso": 2.18,
    "terminal": "F2",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-12120"
  },
  {
    "id": "power-sonic-ps-12180",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 12180",
    "volt": 12.0,
    "ah": 18.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "181 × 76 × 167 mm",
    "peso": 5.72,
    "terminal": "NB",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-12180"
  },
  {
    "id": "power-sonic-ps-12260",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 12260",
    "volt": 12.0,
    "ah": 26.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "167 × 177 × 125 mm",
    "peso": 7.71,
    "terminal": "NB",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-12260"
  },
  {
    "id": "power-sonic-ps-12350",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 12350",
    "volt": 12.0,
    "ah": 35.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "196 × 131 × 176 mm",
    "peso": 11.2,
    "terminal": "NB3",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-12350"
  },
  {
    "id": "power-sonic-ps-12400",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 12400",
    "volt": 12.0,
    "ah": 40.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "197 × 165 × 170 mm",
    "peso": 13.2,
    "terminal": "NB4:",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-12400"
  },
  {
    "id": "power-sonic-ps-12550",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 12550",
    "volt": 12.0,
    "ah": 55.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "230 × 138 × 228 mm",
    "peso": 16.3,
    "terminal": "U",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-12550"
  },
  {
    "id": "power-sonic-ps-12750",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 12750",
    "volt": 12.0,
    "ah": 75.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "260 × 168 × 228 mm",
    "peso": 23.0,
    "terminal": "U",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-12750"
  },
  {
    "id": "power-sonic-ps-121000",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 121000",
    "volt": 12.0,
    "ah": 100.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "305 × 168 × 228 mm",
    "peso": 30.84,
    "terminal": "U",
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-121000"
  },
  {
    "id": "power-sonic-ps-121100",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 121100",
    "volt": 12.0,
    "ah": 110.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "330 × 172 × 212 mm",
    "peso": 32.0,
    "terminal": null,
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-121100"
  },
  {
    "id": "power-sonic-ps-122500",
    "marca": "Power-Sonic",
    "serie": "PS",
    "modelo": "PS 122500",
    "volt": 12.0,
    "ah": 260.0,
    "tipo": "Uso general (VRLA/AGM)",
    "medidas": "522 × 268 × 226 mm",
    "peso": 73.0,
    "terminal": null,
    "imagen": null,
    "fuente": "https://www.stondemand.mx/página-principal/baterias-ácido-plomo/power-sonic/ps-series/ps-122500"
  }
] as Bateria[];

export const MARCAS: Marca[] = ["Power-Sonic", "Kaise", "Dynasty", "Genesis"];

export const MARCA_SLUG: Record<Marca, string> = {
  "Power-Sonic": "power-sonic",
  Kaise: "kaise",
  Dynasty: "dynasty",
  Genesis: "genesis",
};

export const SLUG_MARCA: Record<string, Marca> = Object.fromEntries(
  Object.entries(MARCA_SLUG).map(([m, s]) => [s, m as Marca])
) as Record<string, Marca>;
